// <auto-generated />
namespace project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class relatonships41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relatonships41));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231733449_relatonships41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
